# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!

target 'BSTextDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BSTextDemo
  pod 'BSText'
  pod 'YYWebImage'

  target 'BSTextDemoTests' do
#    inherit! :search_paths
    # Pods for testing
    use_frameworks!
    
    pod 'BSText'
    pod 'YYWebImage'

  end

  target 'BSTextDemoUITests' do
#    inherit! :search_paths
    # Pods for testing
    use_frameworks!
    
    pod 'BSText'
    pod 'YYWebImage'

  end

end
