# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
inhibit_all_warnings!

target 'BSTextDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

def common
    pod 'BSText', :path => "../BSText.podspec"
    pod 'YYWebImage'
end

  # Pods for BSTextDemo
  common

  target 'BSTextDemoTests' do
    inherit! :search_paths
    # Pods for testing
    use_frameworks!
    
    common

  end

  target 'BSTextDemoUITests' do
    inherit! :search_paths
    # Pods for testing
    use_frameworks!
    
    common

  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
