name: BSText Tests

on:
  push:
    branches: [ main, dev, dev/v3.0 ]
  pull_request:
    branches: [ main, dev, dev/v3.0 ]

jobs:
  test:
    name: Test on Xcode
    runs-on: macos-latest
    
    strategy:
      matrix:
        platform: [iOS]
        xcode: [latest-stable]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
        
    - name: Build and test
      run: |
        set -o pipefail
        xcodebuild -scheme BSText -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' -enableCodeCoverage YES clean test | xcpretty
        
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
